
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-authentication-deployment
  namespace: customer-authentication
  labels:
    app: customer-2fa

spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: customer-2fa
  template:
    metadata:
      labels:
        app: customer-2fa
    spec:
      containers:
        - name: customer-authentication
          image: _IMAGE_
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: NEW_RELIC_APP_NAME
              value: "customer-authentication-ms"
            - name: SPRING_PROFILES_ACTIVE
              value: _SPRING_PROFILES_ACTIVE_
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: databasecredentials
                  key: db_pwd_customer_authentication_user
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "700m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 300
            timeoutSeconds: 5
            periodSeconds: 30
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 360
            timeoutSeconds: 5
            periodSeconds: 30
            failureThreshold: 3
      imagePullSecrets:
        - name: customer-authentication
