FROM registry.gitlab.com/krealomine/docker_openjdk_newrelic:latest

ADD postgres.crt /root/.postgresql/root.crt
ADD target/*.jar /opt/ms/customer-authentication-ms.jar

EXPOSE 8080
CMD java -javaagent:/opt/newrelic/newrelic.jar -jar /opt/ms/customer-authentication-ms.jar