server:
    port: 8081
    pattern:
        level: '%X{traceId} %5p'
spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/tenpo_customer_authentication
        username: postgres
        password: postgres
    flyway:
        schemas: customer_authentication
    jackson:
        property-naming-strategy: SNAKE_CASE
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
        show-sql: false
    kafka:
        bootstrap-servers: 137.116.88.31:9092
        consumer:
            group-id: customer-authentication
cloud:
    azure:
        tenantId: cae09fee-473e-48e2-99dc-3b7bf4a97411
        tenantName: tenpodev2.onmicrosoft.com
        version: 1.6
        clientId: 02c93c97-0b97-48ba-b2d7-97428d8677df
        clientSecret: 7waH5xiFfOjEkOy9uWrFaitCOXB7OOOR1PanHnj77iE=
        userFlowName: B2C_1_ROPC_mobile
        userClientId: 5cba8f4d-b819-4903-a414-732dbd4b8378
        blobStorageConnectionString: 'DefaultEndpointsProtocol=https;AccountName=tenpodevstorageaccount;AccountKey=vsKf9z2VVaM7vUdEUjn4VtEMha8n5oheGOP+dX4FhuXET/D6SfzSlVnDe3GtGoJ6qTEZTTBit5Ks8ak1vrDBOw=='
        blobStorageContainerName: tenpodevstoragecontainer
        api-graph:
            base-url: https://graph.windows.net
            getAccessTokenResourcePath: https://login.microsoftonline.com/${cloud.azure.tenantId}/oauth2/v2.0/token
            getLoginAccessTokenResourcePath: https://tenpodev2.b2clogin.com/${cloud.azure.tenantId}/oauth2/v2.0/token?p=${cloud.azure.userFlowName}
            userMaintenanceResourcePath: ${cloud.azure.api-graph.base-url}/${cloud.azure.tenantId}/users
            changePasswordResourcePath: ${cloud.azure.api-graph.base-url}/${cloud.azure.tenantId}/users
            resetPasswordResourcePath: ${cloud.azure.api-graph.base-url}/${cloud.azure.tenantId}/users
krealo:
    security:
        disabledFor:
            - /**
    cloud:
        accounts:
            implement: real
        users:
            baseUrl: http://user-ms:8080
            getUserByIdResourcePath: ${krealo.cloud.users.baseUrl}/${krealo.cloud.version}/user-management/users/{userId}
            implement: mock
        notifications:
            implement: real