server:
    port: 8088
    pattern:
        level: '%X{traceId} %5p'
spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/tenpo_customer_authentication
        username: postgres
        password: postgres
    flyway:
        schemas: customer_authentication
    jackson:
        property-naming-strategy: SNAKE_CASE
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
        show-sql: false
krealo:
    security:
        disabledFor:
            - /**