package cl.tenpo.customerauthentication.externalservice.notification.dto;

public enum NotificationEventType {
    RECHARGE_SERVICE,
    SERVICE_PAYMENT,
    TRANSFER_OTHER_BANKS,
    TRANSFER_MINER,
    REQUEST_TRANSFER_MINER,
    REQUEST_TRANSFER_SENDER ,
    REQUEST_TRANSFER_RECEIVER,
    CASH_IN_VIRTUAL,
    CASH_IN_PRESENTIAL,
    CASH_OUT_VIRTUAL,
    CASH_OUT_PRESENTIAL,
    PURCHASES,
    VERIFICATION_CODE,
    ACTIVATED_CARD,
    RETRY_ACTIVATION,
    BLOCKED_CARD,
    LIMITED_USER,
    ON_BOARDING_SUCCESS,
    ON_BOARDING_CONTINUE,
    BLACK_LIST_SUCCESS,
    BLACK_LIST_WRONG,
    CARD_REQUEST,
    BLOCKED_USER,
    CLOSED_ACCOUNT
}
